### ISSUE TITLE
可以支援Twitter圖片顯示嗎？

### ISSUE THREAD

**Issue by NiGHTsC** [eight04/ptt-imgur-fix#13]
請問有時間的話，可以也支援twitter的圖片顯示嗎？
https://www.ptt.cc/bbs/C_Chat/M.1593802435.A.DC4.html

pbs.twimg.com這類的圖片

謝謝。

**Comment by eight04** [comment]
Twitter 一直是有支援的吧

**Comment by NiGHTsC** [comment]
您這麼一說，我才發現在Chrome v91是不用裝這個也能直接顯示Twitter
但是在FF v68則是有裝沒裝都不能顯示
![](https://i.imgur.com/EJAdSTn.jpg)

**Comment by eight04** [comment]
是不是被追蹤保護功能擋掉了︰https://www.ptt.cc/bbs/Browsers/M.1626183143.A.4AB.html

**Comment by NiGHTsC** [comment]
真的是專家，一看就知道答案！
已加入追蹤白名單！

謝謝您！
