### ISSUE TITLE
not work in greasemonkey 4.11

### ISSUE THREAD

**Issue by GHolk** [eight04/ptt-imgur-fix#14]
GreaseMonkey 4.11 把 `GM_*` 等 api 更名為 `GM.*` ，所以 `GM_config` 那支腳本不能執行。
這裡提供二個解法：

用現成的 shim patch 出那幾個函數，
greasespot 上提到 [這支腳本](https://wiki.greasespot.net/@grant) ：
`@require https://gist.githubusercontent.com/arantius/3123124/raw/grant-none-shim.js`
但他沒有實作 `GM_registerMenuCommand` ，所以還是要改其它地方。

手動 polyfill ，你的腳本只用了 getValue setValue registerMenuCommand ，
patch 起來不會太難，我試試看 patch 。

**Comment by eight04** [comment]
我認為比較好的方法是移除 GM_config，我現在沒怎麼在維護 GM_config 了︰

1. 移除 GM_config，轉換到 [GM_webextPref](https://github.com/eight04/GM_webextPref)，類似 [Linkify Plus Plus](https://github.com/eight04/linkify-plus-plus/blob/master/src/userscript/index.js)
2. 修正 https://github.com/eight04/GM_webextPref/issues/5

----

老實說我不喜歡幾年前 arantius 處理 issue 和 pr 的態度，現在不知道如何。

**Comment by GHolk** [comment]
所以你要修嗎？沒有維護沒關係，可以動就好了。

關於 arantius 不知道，我還是終端的使用者。
頂多之前有修過 greasespot wiki 而已，所以有申請進 mailing list。
另外 `GM.*` 這幾項更新 tamper violent 也的確都沒有跟進。

**Comment by eight04** [comment]
> 所以你要修嗎？

可以。不過從 GM_config 跳到 GM_webextPref 會是一個 breaking change，設定不會自動繼承。

> 另外 `GM.*` 這幾項更新 tamper violent 也的確都沒有跟進。

Violentmonkey 跟 Tampermonkey 都有支援 `GM.*` API，同時保留原本的 `GM_*` API。

**Comment by GHolk** [comment]
原來，我看 tamper monkey 的文件只有 `GM_*` ： https://www.tampermonkey.net/documentation.php
