### ISSUE TITLE
載入大量youtube網址之網頁時需要重複點擊多次上一頁才能離開該頁面

### ISSUE THREAD

**Issue by BHXNY** [eight04/ptt-imgur-fix#22]
for test:
https://www.ptt.cc/bbs/C_Chat/M.1669025185.A.60C.html

https://i.imgur.com/gwoUeLO.png

chrome version:107.0.5304.107
edge version:107.0.1418.52
皆確認有該問題發生

**Comment by eight04** [comment]
https://stackoverflow.com/questions/24407573/how-can-i-make-an-iframe-not-save-to-history-in-chrome
