### ISSUE TITLE
Twitter webp issue

### ISSUE THREAD

**Issue by eight04** [eight04/ptt-imgur-fix#26]
Twitter starts using webp but it doesn't support old API?
```
https://pbs.twimg.com/media/F3Nq3aSbAAAJufG?format=webp&name=small // source
https://pbs.twimg.com/media/F3Nq3aSbAAAJufG.webp:small // doesn't work
https://pbs.twimg.com/media/F3Nq3aSbAAAJufG.jpg:small // work
```

**Comment by cldotdev** [comment]
Doesn't work with Twitter images:

![圖片](https://github.com/eight04/ptt-imgur-fix/assets/2265716/7cef350f-d6f9-49ee-84fc-be6e0ba900e9)

Example link:

https://www.ptt.cc/bbs/C_Chat/M.1698847794.A.0F3.html

**Comment by eight04** [comment]
Fixed in 0.8.1

**Comment by cldotdev** [comment]
Still no image

![圖片](https://github.com/eight04/ptt-imgur-fix/assets/2265716/1b115524-aa7f-4779-8950-f0a1f962ce39)

**Comment by eight04** [comment]
你的問題看起來和這個issue無關。錯誤訊息寫「內容封鎖功能」，你看看圖片是不是被Tracking Protection擋掉了
https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_protections-dashboard

**Comment by cldotdev** [comment]
> 你的問題看起來和這個issue無關。錯誤訊息寫「內容封鎖功能」，你看看圖片是不是被Tracking Protection擋掉了 https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_protections-dashboard

確實是被 Firefox 加強型追蹤保護擋掉了，Reddit 有人分享 [about:config 的設定](https://www.reddit.com/r/firefox/comments/wvhg55/comment/ilfxf15/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)可以設為白名單，設定完就可以正常顯示了。

```
urlclassifier.trackingSkipURLs = *.twitter.com, *.twimg.com
urlclassifier.features.socialtracking.skipURLs = *.twitter.com, *.twimg.com
```
