### ISSUE TITLE
腳本開啟時會導致PTT無法讀取推特圖

### ISSUE THREAD

**Issue by seventhsky** [eight04/ptt-imgur-fix#5]
如題
腳本開啟時可以正常讀imgur 但推特圖會掛掉
關掉後推特圖就恢復正常

**Comment by eight04** [comment]
我這裡測試正常。連結和你使用的瀏覽器是？

**Comment by seventhsky** [comment]
隨便找的連結
https://www.ptt.cc/bbs/C_Chat/M.1595952700.A.FF7.html

瀏覽器是Microsoft Edge 85.0.564.18
偶爾會發作
總是會有幾張圖讀不出來
我再看看是不是其他原因造成的好了

補充:試過關掉其他腳本跟擋廣告套件沒用 只有關掉這個推特圖才能正常讀取

**Comment by eight04** [comment]
看起來問題在於大圖的網址。原圖的網址是
```
https://pbs.twimg.com/media/EeA1ae6UMAADhyy.jpg
```
腳本會嘗試讀取大圖
```
https://pbs.twimg.com/media/EeA1ae6UMAADhyy.jpg:orig
```
然而真正的大圖網址是
```
https://pbs.twimg.com/media/EeA1ae6UMAADhyy.png:orig
```
